POST http://localhost:8080/user/create HTTP/1.1
content-type: application/json

{
    "name":"sai sumith",
	"dob" :"15/03/2004",
	"sex" :"M",
	"mobile": "0505896371",
	"govtID": {
        "idType": "adhar",
	    "id":"1234"
    },
	
	"guardian": {
        "label":"father",
        "name":"vinod"
    },
	"email": "saisumith@gmail.com",
	"emergencyNumber": "124598996",
	
	"address": "home",
	"country": "india",
	"state":"telangana",
	"city" :"hyderabad",
	"pincode": "123",
	
	"occupation":"student",
	"religion":"hindu",
	"marritalStatus": false,
	"bloodGroup":"O+",
	"nationality" :"indian"
}
